### ISSUE TITLE
Automated httr authentication using  "options(httr_oauth_cache = TRUE)"

### ISSUE THREAD

**Issue by patperu** [bradleyboehmke/R-APIs#1]
Hello,
thank you for your post, it's really instructive! I have just a small note: If you run the httr authentication inside a function you are always prompted for a response. You can surpress this by setting the 'httr_oauth_cache' option to TRUE (see also http://stackoverflow.com/q/28221405).
Maybe it's worth mentioning....
Ciao
Patrick

**Comment by bradleyboehmke** [comment]
Great input Patrick. I added your comment to the post. Thanks.
